---
title: "Zeus and Prot"
date: 2023-08-29T13:28:31+02:00
draft: false
author: "Summer Emacs"
tags: ["screenplay","emacs","misc","satire","comedy"]
---

After coming home, I started reviewing Prot's progress with the hut this morning. I saw his video post about a pomegranate tree which had mysteriously sprouted. Also, I saw him working like crazy to build this hut. So, after putting some odd links together in my head, I came up with the following screenplay. 🙃 I wrote this really fast so I hope it comes across as okay.


* Zeus and Prot - A Discussion

SCENE: The end of winter, 2023. Prot is typing away at his computer as evening darkens the windows.

PROT: (Speaking to himself as he re-reads what he has written) So, given the societal impact of the Antikythera mechanism on ancient lives, and the philosophical foundations of machinery and fundamental programming introduced in a primitive society, we can....

ZEUS: (As a disembodied and loud voice): Prot.

PROT: (Startled, looks around): Eh? Is somebody there? (Look around some more) Who is this? Spyware doesn't work on my GNU Linux system. What is going on?

ZEUS: Prot. Listen. It's me. Zeus.

PROT: Zeus? (Takes off his glasses) What? Are you a hacker? I should inform you that I am very good with comp-

ZEUS: No, Prot. I'm not a hacker. I'm the God - Zeus. The King of the Gods.

PROT: What? Are you serious? You know I don't believe in you. I'm an atheist. You don't exist. You're an interesting sociological and mythological figure from ancie-

ZEUS: I know, I know. Trust me, I'm real. It doesn't matter if you don't believe-

PROT: Yes, and you know that belief is not counted among the virtues in ancient Greek reli-

ZEUS: I know! We're better than the other guys. Listen, this is more important. I have a message for you.

PROT: What? You have a message for me? (Pauses..) What is this about? How do I know that you're really Zeus?

ZEUS: I'll show you later! Just /listen/ for a moment! (Pauses...papers can be heard shuffling in the background) I'm trying to find my announcement. I had it written up.

PROT: You know, if you had used Emacs, then you could have used =consult-ripgrep= and-

ZEUS: Yes! Yes, I know. But I grew up with clay tablets and papyrus. Call me old fashioned, but it's hard to change.

PROT: Yes, but as you know, in philosophy, we like to think that change is reflective of a positive outloo-

ZEUS: Found it! (Pauses for a moment) Now, where were we? Ah...yes. Here! (Pauses for overly dramatic effect and resumes with a great booming voice) Prot! I task you with a task of momentous import! (There is silence for a little while)

PROT: Yes..? What task? Is this a God-like imperative or some kind of very pressing request? Because the two would be diffe-

ZEUS: I'm sorry, I was trying to read my handwriting. It got a little smudged. Ah, here we are. (Resumes the great booming voice) Prot! I task you to go out into the wilderness! (He pauses again) I think they call it "Going off the grid" these days. You're familiar with the term?

PROT: Yes. Yes of course. I often take hikes in nature and-

ZEUS: (Sounding overly pleased) *Very good!* Right, then! (Resumes booming voice) Prot! I task you to go into the wilderness, find a secluded and survivable spot, and build...(there is a dramatic pause)... /a/ /hut/!

(There is a long pause)

PROT: You want me to /what/? It sounded like you said you wanted me to build a-

ZEUS: A /hut/! Yes! I want you...to build a hut. That's what is written right here. A hut. Off the grid. And there is a note in the margins here amongst the doodles which says "It must be self...sufficient".

(Another pause)

PROT: Zeus, I do not mean to be disrespectful, especially if you really /are/ a God, but why would I do this? Why is it so important?

ZEUS: It is not just important to you, but important to the world, Prot!

PROT: The world?!

ZEUS: Yes. The world. It has a divine purpose.

PROT: I don't understand. Why would my building a hut be so important to anything?

ZEUS: Well, you see...(He sighs deeply)...can we speak frankly for a moment?

PROT: I have always spoken frankly and clearly as far as I remember, Zeus. It is part of my philo-

ZEUS: (Gives a huge sigh) Things aren't going well, Prot. Things aren't going well at all.

PROT: (Furrows his brow and starts to clean his glasses) Oh? Maybe I can help you. I like to help create solutions to problems in many different capaci-

ZEUS: It's the world, Prot. You can't fix the world. Not even I can do it. And Hera's been nagging me for the last century to do something about it and I can't shut her up! Nag, nag, nag! Well, you've heard all of the old stories, I'm sure.

PROT: Indeed. We studied this in my old class when I was a boy and-

ZEUS: (Gives another long and depressed sigh) Prot...she won't stop. I have to do /something/! So, I'm going to. I'm going to end the world.

PROT: /WHAT??!/

ZEUS: By fire.

PROT: WHAT??!!

ZEUS: ...and start it over again.

PROT: You're actually going to burn the whole world??!!

ZEUS: Well, I wanted Poseidon to flood it, but we're going for more equal representation up here. So the council has voted that it's Hephaestus' turn this time around.

PROT: Oh.

ZEUS: Yes. It's time I fixed things a little better. But, as you know, sometimes rearranging blocks of things just won't fix something if it's rotten to the core. Sometimes, you need to start a new buffer. (Pause) Is that terminology closer to your understanding?

PROT: (Doesn't know what to say for a moment...) Yes...Yes I understand, but I don't agree with it!

ZEUS: What don't you agree with?

PROT: Ending the world isn't like wiping out a buffer! it's wiping out people! These are not characters on a screen, but living and thinking beings! Can't you just... (He waggles his hands and fingers) you know...aren't you a /God/? Or so you claim!

ZEUS: Prot. If I'm going to wipe out the world, won't that be enough evidence for you that what I'm saying is true? That I /am/ a God?

PROT: Ah. Interesting question! Perhaps. But you could be a malicious alien being of some kind...

ZEUS: This isn't the time for a theological debate, Prot. I'm telling you: I have great plans for you. Now, listen!

PROT: I still can't believe this is happening. I must have had some bad feta cheese tonight.

ZEUS: No, it wasn't any bad feta cheese, Prot. I'm real. Now, sit down and listen.

(Prot sits down in his chair, staring at his screen, dumbfounded.)

ZEUS: I want you to build a hut because I want you to survive this calamity. You will be amongst the very few who do. And you will spread a better philosophy to the new people - a philosophy of freedom, thought, rationality, and Emacs. I have chosen you, Prot, to spread this message. Your naturally calm demeanor and inclination to educate shall be needed to soothe them after this calamity.

PROT: Okay. I can see there is some thought to this, and not just an overreaction to your wife's badgering, but please won't you consider-

ZEUS: I have considered everything! Listen. You will go into the mountains and build yourself a hut. It will be isolated and there will be much hard work to prepare for the day! You will toil for months in the hot sun. But the price will be your own survival and this shall be part of your reward.

PROT: Okay. Let us assume that you are correct in your presentation of everything so far. What about my own place here? You want me to just move at the drop of a hat?

ZEUS: Oh, don't worry about that. I turned your landlord into a complete jackass. He'll be increasing the rent so that you can't afford it.

PROT: /WHAT??!!/ WHY? Why would you do that??!!

ZEUS: Well, to make sure that you move, of course. To give you...what's that thing that humans need? (He pauses, searching) "Incentive"! Yes! That was it! "Incentive!" I have given you..."/Incentive/"! (He sounds very proud of himself)

PROT: But...but...! (He splutters in a most un-Prot-like fashion)

ZEUS: (Completely oblivious of his own overbearing behavior) Yes. I'm quite proud of my solutions overall. Some might call them "Draconian", but I prefer to think of them as "resolute". I like that word.

PROT: (Shouting) /WHAT GIVES YOU THE RIGHT??!!/

ZEUS: (He pauses for a moment) I'm...a God, Prot.

PROT: But, you're not /real/! None of this can be real!

ZEUS: (Voice booming again) Oh?! Well, I shall prove it to you! I shall scorch the earth this summer as evidence of my later intentions. It shall be the hottest ever known. It shall be so hot that all of those massively popular tourist places in Greece shall close down due to the heat alone for the first time in their history! /THEN/ you shall see!

PROT: Wait! Wait a moment...please...

ZEUS: No. No, my mind is made up. You build that hut or it'll get worse. Trust me, it can. And you'll want to in the end.

PROT: Can we not discuss this in a calm and rational mann-

ZEUS: Nope. I'm being resolute, remember? Now, listen, this is important.

PROT: Are you cer-

ZEUS: Yes. Now... (He pauses for a moment) You shall build the hut large enough to accommodate yourself and  a family of four! So it shall be a big hut! But don't ask me how big because numbers aren't something that I do. I mean, look at the monetary system in ancient Greece - it was a logical disaster...

PROT: Okay. I am calming down. Who is this family?

ZEUS: David Wilson and his family. He's also a free software guy into Emacs. And he's in Greece. He too shall survive the coming apocalypse.

PROT: Ah. Yes. David. A good person. Does he know about this?

ZEUS: No. I shall reveal it to him when the time is right. If I told him beforehand, he might blurt it out by accident in one of his weekly livestreams, and then the whole operation would be ruined. Also, there will be some other survivors, but they won't be staying at your hut. I don't want to overly inconvenience you.

PROT: You don't think of any of this as a catastrophic inconvenience, Zeus?

ZEUS: You are as stubborn as Achilles, Prot! No, I am /saving/ you!

PROT: So you say. Tell me, Zeus: (Sounding very sarcastic) Do you want me to also bring in every animal two by two?

ZEUS: What? No! That's the other guy! I'll just make all the animals again. There's no need to save any. What a stupid plan that was.

PROT: I agree. At least we can agree on something.

ZEUS: Anyway, I can't save the animals because I have to make new ones. I promised to correct some things this time around.

PROT: What? What promise? What corrections?

ZEUS: Weeelll....I promised to make pink horses, ponies, and unicorns this time around. And a few other things.

PROT: Ah.

ZEUS: Also dogs that don't shed or drool, cats that don't need litter boxes, bears that don't bite, and new elephants. She wants new elephants.

PROT: Elephants?

ZEUS: Yes. Pink ones. That can fly.

PROT: Surely, you must be jok-

ZEUS: I know! I know...but she made me promise. And Hera thought it was a nice idea too.

PROT: So who is this person?

ZEUS: This girl wanted them. She's one of the elect, like you.

PROT: ...I think I know who you mean....

ZEUS: Yes. Hyperactive and sometimes a little assertive.

PROT: Tell me about it.

ZEUS: Yes. A little corrupt in the "Free as in freedom" department, but Hera's been a fan of some of her fashionable posts since a while so I had to promise.

PROT: I know she's assertive, but /you've/ decided to wipe out the world, Zeus.

ZEUS: Yes, well...now...Back to business! I want you to live a simple life during this time. You will set the way for the new humans. It will be a better world, like it was in the beginning. I shall send you down some muses sometimes to guide you. And I shall bless your land with a pomegranate tree out of thin air.

PROT: A what?

ZEUS: A pomegranate tree. You like pomegranates, don't you?

PROT: Of course. They are very tasty. I often thought that if I use their seeds in a dish I like to prepa-

ZEUS: And it shall appear out of nowhere! You shall be surprised!

PROT: But you just told me that this would happen. So how can it surprise me?

ZEUS: Oh that's simple. I shall erase your memory of this part of the conversation. You will take it later on as a sign when you discover it.

PROT: Okay. You understand that you are breaking all kinds of philosophical boundaries here about free will, determinism, theo-

ZEUS: Never mind all of that! I shall give you this sign, unbeknownst to you, and you shall be pleased.

PROT: Alright. I suppose that I should thank you.

ZEUS: You are welcome! Now, do you have any idea about how to build a hut?

PROT: No.

ZEUS: Are you sure? You seem to be a practical man to me, so I just assumed that you could.

PROT: I assure you that I have no house building experience at all.

ZEUS: Well, just do your best. I'm positive that you'll excel at the endeavor. Okay, well that's all wrapped up for now. I have to go and wash the dishes from our feast this evening or Hera will be displeased yet again.

PROT: Wait! You're just going to leave? How do I know this isn't some strange dream or hallucination?

ZEUS: (Voice booming) REMEMBER MY PROPHECY ABOUT THE SUMMER!

PROT: Ah. Yes. But you want me to start now?

ZEUS: Naturally.

PROT: But where do I go?

ZEUS: Into the hills! I told you! Now go! I shall check in on you later.

PROT: Very well. Zeus...one more thing.

ZEUS: Yes? What is it?

PROT: After speaking with you, I would like to say that I just wish my position on atheism had been correct, because you are one hell of a fu-

ZEUS: Just go! Do as I say! I shall drop in later to see if you are performing my task.

PROT: (Sighing a big exhausted sigh) Okay Zeus.

